GET http://localhost:3000

###

Get http://localhost:3000/check
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Iktob28iLCJwYXNzd29yZCI6IjExMjIzMyIsIm5hbWUiOiJLaG9vIiwiZW1haWwiOiJraG9vQHN0dWRlbnQudXRlbS5lZHUubXkiLCJpYXQiOjE2ODEzNzIxNzcsImV4cCI6MTY4MTM3Mjc3N30.z1TKAwB20l7icVq-p-6-zQD2d7ku2e7nOYxl9ErkUCM

###

POST http://localhost:3000/login
Content-Type: application/json
//define the content type ---> json
{
    "username" : "KHOO",
    //"password" : 111111
}

###
POST http://localhost:3000/register
//define the content type ---> json
Content-Type: application/json

{
    "username" : "GOH",
    "password" : 111111,
    "name"     : "Goh Jia Xuen",
    "email"    : "goh@student.utem.edu.my"
}